---
title: "Fit a GLARMA model to MIMIC dataset"
output: pdf_document
---

```{r, echo=FALSE}
library(glarma)
library(forecast)
library(plyr)
library(dplyr)
library(here)
source(here::here("R/CombinedOnlineSL.R"))
source(here::here("R/utils_mimic.R"))
```

```{r}
#Load data:
data<-load(here::here("Data/data.Rdata"))

#Pick 500 samples that have period 1,2 3, 4 and 5:
train_all <- sample_n_t(df, n = 500, t=5)
samples<-unique(train_all$subject_id)

#Samples that EVER had event:
sample_event<-train_all %>% group_by(subject_id) %>% summarise(Frequency = sum(Y1))  %>%
  mutate(Event = ifelse(Frequency > 0, 1,0))

#PROBLEM: How to deal with missing values?
#NAs: sapsi_first,sofa_first, bmi, los_hospital
summary(train_all)
train_all <- train_all[,-c(2,6,7,8,10,12)]

#Convert character to numeric:
#gender, admission_type_descr
train_all$gender <- ifelse(train_all$gender=="M",1,0)

#Create a new outcome:
train_all <- new_Y_sol1(train_all = train_all)

#Specify the covariates and outcome:
covars_wbaseline <- c("gender","age","care_unit",
                      "los_icu","amine","sedation","ventilation","spo2","abpsys",
                      "abpdias","abpmean")
covars <- c("los_icu","amine","sedation","ventilation","spo2","abpsys","abpdias","abpmean")
```

```{r}
### ARIMA
#Issue: this is an interrupted time-series... "Seassonality" in individuals
fit_arima_global <- forecast::auto.arima(train_all$abpmean)

#this is a univariate method, see robustness across individuals
fit<-list()
fit_coef<-list()
counter<-1
for(i in samples){
  sub <- train_all[train_all$subject_id==i,]
  fit[[counter]] <- forecast::auto.arima(sub$abpmean)
  fit_coef[[counter]]<-fit[[counter]]$coef
  counter<-counter+1
}

#If model can't be estimated, specify:
fit_coef<-lapply(fit_coef, function(x) if(identical(x, numeric(0))){x<-"No model"}else{x})
fit_coef_all<-do.call("rbind.fill", lapply(fit_coef, function(x) data.frame(as.list(x))))
#Add sample names and if ever event happened
fit_coef_all<-cbind.data.frame(sample_event,past=rowSums(!is.na(fit_coef_all)),fit_coef_all)
#How many samples with AR and MA terms?
fit_coef_all$ar<-rowSums(!is.na(fit_coef_all[,grep("ar",names(fit_coef_all))]))
fit_coef_all$ma<-rowSums(!is.na(fit_coef_all[,grep("ma",names(fit_coef_all))]))
write.csv(fit_coef_all, here::here("Results/ARIMA_fits_n500.csv"), quote = FALSE, row.names = FALSE)

#Are there differences in the length of past relevant if you had event/did not have event?
fit_coef_all %>% group_by(Event) %>% summarise_at(vars(past), funs(mean(., na.rm=TRUE)))
fit_coef_all %>% group_by(Event) %>% summarise_at(vars(ar), funs(mean(., na.rm=TRUE)))
fit_coef_all %>% group_by(Event) %>% summarise_at(vars(ma), funs(mean(., na.rm=TRUE)))

 
### Model with glarma
Y<-cbind.data.frame(Y1=train_all$Y1,Y0=1-train_all$Y1)
#X<-data.frame(Intcpt=rep(1,nrow(train_all)), train_all[,covars])
X <- data.frame(Intcpt=rep(1,nrow(train_all)), abpdias=train_all$abpdias, 
                abpsys=train_all$abpsys, abpmean=train_all$abpmean)

#Do not specify any of the lags
#Use binomial distribution to model the counts
#Fisher scoring for estimating the parameters of glarma
#Pearson residuals 
bin_fit<-glarma(y=train_all$Y1, thetaLags = c(1,2,5), X=train_all$abpmean, type="Poi")


```

